### ISSUE TITLE
I don't even have an e: installed, and it started doing this mid-editing.

### ISSUE THREAD

**Issue by Emilinrose** [G3HS/Secret-Tool#13]
so i was editing hydreigion, and this happened. I'd already repointed the moveset to have all 13 moves(there were only ten before.) then when editing the moves, it imploded.

[Window Title]
Piped error from sys.stderr: PLEASE REPORT

[Main Instruction]
ERROR:

[Content]
Traceback (most recent call last):
  File "E:\Secret-Tool\build\mainWIN\out00-PYZ.pyz\wx._core", line 16767, in <lambda>
  File "<string>", line 438, in reload_all_tabs
  File "<string>", line 454, in __init__
  File "<string>", line 540, in __init__
  File "<string>", line 723, in __init__
  File "<string>", line 784, in __init__
  File "<string>", line 1015, in generate_ui
  File "E:\Secret-Tool\build\mainWIN\out00-PYZ.pyz\lib.Tools.rom_insertion_operations", line 104, in generate_list_of_names
IOError: [Errno 22] Invalid argument

[OK]

**Comment by cosarara97** [comment]
That path with an e: is not on your computer, but where the tool executable was built. Anyway, if you give the detailed steps on how to make the program crash like this I guess I could take a look at it.
