### ISSUE TITLE
Can't open ROM files

### ISSUE THREAD

**Issue by cattichu** [G3HS/Secret-Tool#14]
Opened the program successfully (although I had to move the _Gen_III_Suite.exe_ file from the **dist** folder into the **Gen_III_Suite (MAC)** folder so it would find the _Icon.png_ file correctly at startup).

I'm new to all this so I don't know what I'm doing and might be missing something obvious, but I
1) Tried opening a random FireRed ROM base
2) Tried opening MrDollSteak's v1.5 base, since it was mentioned in the help documentation

and I got the same errors both times. 

**First error:**

`"At rom offset 0xfffffe there is an unknown rom id. This means that your rom has a number at the offset of the rom id that is not in the ini. Would you like to overwrite this number with a new one? Please note that this could result in data loss, if, for example, there was an image at that location causing this issue. If no, then this program will close."`

-> I hit "Yes".

**Second error:**
"Piped error from sys.stderr: PLEASE REPORT"
```
Error: 

Traceback (most recent call last):
    File "/Users/homedepot326/Desktop/Secret-Tool-master/build/mainMAC/out00-PYZ.pyz/wx._core", line 16767, in <lambda>
    File "<string>", line 403, in work_with_ini
    File "/Users/homedepot326/Desktop/Secret-Tool-master/build/mainMAC/out00-PYZ.pyz/wx._core", line 3623, in __init__
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xa4 in position 9: ordinal not in range(128)
```

Thanks!

**Comment by cosarara97** [comment]
The "first error" is expected and not an error. Since you've closed this, did you manage to fix the second issue?

**Comment by ogrif11** [comment]
I get this error but on a mac. It needs to be fixed.

**Comment by cosarara97** [comment]
Explain what error you got exactly, and the steps to trigger it. Don't get your hopes too high for a fix, but we can probably find a work-around.

**Comment by thekaratekid552** [comment]
This error is the biggest error in the program and one that I personally spent way too much time on. It is due to the fact that the locale settings for Python 2 defaulted to ASCII, so bytes not in that set couldn't be decoded. Python 2 also doesn't have a separate type for bytes, which is why there is a lot of hacking around create binary strings in the program. This project really needs to be rewritten in Python 3 using PyQt, which has a dedicated bytes object in the standard types and defaults to Unicode.  This is something I would really like to do when I have some free time.

As a work around for now, it would probably work well on Mac if you run the source code directly. Macs come preinstalled with Python 2 and then use Pip to install the requirements listed. Launch a terminal, cd into the source directly and run 'python main.py' and it should be better.


@cosarara97: I've been gone for a long time, I'm sorry about leaving you with this project when my life suddenly got really busy and I had no time for it. Thank you so much for taking care of it.  I still don't have a lot of time, but I think I should be able to work on it in a month or so. I'm really hoping to.
